# Generated by Django 4.1.7 on 2023-05-25 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0010_delete_categoryspecifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ключ_сессии')),
                ('status', models.CharField(choices=[('Нов', 'Новый заказ'), ('Обр', 'В обработке'), ('При', 'Принят'), ('Дос', 'Доставляется'), ('Вып', 'Выполнен'), ('Отм', 'Отменено')], default='Нов', max_length=3, verbose_name='Статус_заказа')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('note_order', models.TextField(verbose_name='Примечание к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.BooleanField(default=False, verbose_name='Оплата заказа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол-во_товара(шт)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена_по_количеству')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produkt', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'ЭлементЗаказа',
                'verbose_name_plural': 'ЭлементыЗаказа',
            },
        ),
    ]
