# Generated by Django 4.1.7 on 2023-05-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note_order',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание к заказу'),
        ),
    ]
