# Generated by Django 4.1.7 on 2023-05-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_total_price_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItem',
        ),
    ]
