# Generated by Django 4.1.7 on 2023-06-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_address_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Нов', 'Новый заказ'), ('Обр', 'В обработке'), ('При', 'Принят'), ('Дос', 'Доставляется'), ('Вып', 'Выполнен'), ('Отм', 'Отменено'), ('Воз', 'Возврат')], default='Нов', max_length=3, verbose_name='Статус_заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.order', verbose_name='Заказ'),
        ),
    ]
