# Generated by Django 4.1.7 on 2023-05-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_wish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='a_wish',
            table='Wish',
        ),
    ]
