# Generated by Django 4.1.7 on 2023-04-11 20:00

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Префикс')),
            ],
            options={
                'verbose_name': 'Префикс',
                'verbose_name_plural': 'Префиксы',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='shop/%Y/%m/%d', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Слаг')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published', models.BooleanField(default=True, verbose_name='Публикация товара')),
                ('discount', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'нет скидки'), (5, '5%'), (8, '8%'), (10, '10%'), (12, '12%'), (15, '15%'), (20, '20%')], default=0, verbose_name='Скидка')),
                ('sku', models.CharField(max_length=15, unique=True, verbose_name='Артикул')),
                ('count_sold', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Кол-во проданных товаров')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.prefix', verbose_name='Префикс')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Отписание')),
                ('perents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.reviews', verbose_name='Родитель')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produkt', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование характеристики')),
                ('value', models.CharField(max_length=30, verbose_name='Значение')),
                ('products', models.ManyToManyField(blank=True, related_name='feature', to='shop.produkt', verbose_name='Продукт(ы)')),
            ],
            options={
                'verbose_name': 'Характиерстика продукта',
                'verbose_name_plural': 'Характеристики продуктов',
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='produkt_images/%Y/%m/%d', verbose_name='Изображение продукта')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produkt', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение к продукту',
                'verbose_name_plural': 'Изображение к продуктам',
            },
        ),
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Наименование характеристики')),
                ('value', models.CharField(max_length=30, verbose_name='Значение')),
                ('categories', models.ManyToManyField(blank=True, related_name='feature', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Характиерстика категорий',
                'verbose_name_plural': 'Характеристики категорий',
            },
        ),
    ]
