# Generated by Django 4.1.7 on 2023-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productfeature_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отзыва'),
        ),
    ]
