# Generated by Django 4.1.7 on 2023-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_reviews_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfeature',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='feature_category', to='shop.category', verbose_name='Категория'),
        ),
    ]
