# Generated by Django 4.1.7 on 2023-05-19 17:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_categoryspecifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40, verbose_name='Наименование характеристики')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='feature_specifications', to='shop.category', verbose_name='Категория')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childrens', to='shop.categoryspecifications', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'ХарактиерстикаК',
                'verbose_name_plural': 'ХарактеристикиК',
            },
        ),
    ]
