# Generated by Django 4.1.7 on 2023-05-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_categoryspecifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySpecifications',
        ),
    ]
