# Generated by Django 4.1.7 on 2023-05-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_produkt_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='categoryfeature',
            table='CategoryFeature',
        ),
        migrations.AlterModelTable(
            name='imageproduct',
            table='ImageProduct',
        ),
        migrations.AlterModelTable(
            name='prefix',
            table='Prefix',
        ),
        migrations.AlterModelTable(
            name='productfeature',
            table='ProductFeature',
        ),
        migrations.AlterModelTable(
            name='produkt',
            table='Produkt',
        ),
        migrations.AlterModelTable(
            name='reviews',
            table='Reviews',
        ),
    ]
