# Generated by Django 4.1.7 on 2023-05-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_category_table_alter_categoryfeature_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='count_sold',
        ),
    ]
